import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const reactShellSource = readFileSync(new URL("../workbench-web/src/main.tsx", import.meta.url), "utf8");
const pdfPreviewSource = readFileSync(new URL("../workbench-web/src/pdf-preview.tsx", import.meta.url), "utf8");
const scienceViewersSource = readFileSync(new URL("../workbench-web/src/science-viewers.tsx", import.meta.url), "utf8");
const reactShellStyles = readFileSync(new URL("../workbench-web/src/styles.css", import.meta.url), "utf8");
const railActionsSource = reactShellSource.match(
	/<div className="rail-actions">[\s\S]*?<\/div>\s*\n\s*<div className="session-heading">/,
)?.[0] ?? "";

test("React workbench source owns the project Files and artifact inspection surfaces", () => {
	assert.match(reactShellSource, /className="rail-actions"/);
	assert.match(railActionsSource, /<span>New chat<\/span>/);
	assert.match(railActionsSource, /<span>Customize<\/span>/);
	assert.match(railActionsSource, /<span>Files<\/span>/);
	assert.doesNotMatch(railActionsSource, /<span>Search<\/span>|<span>Notebook<\/span>|<span>Compute<\/span>|<span>Memory<\/span>/);
	assert.match(reactShellSource, /className="project-header"/);
	assert.doesNotMatch(reactShellSource, /className="project-card"/);
	assert.match(reactShellSource, /function ProjectLauncher/);
	assert.match(reactShellSource, /className="launcher-project-card"/);
	assert.match(reactShellSource, /<span>New project<\/span>/);
	assert.match(reactShellSource, /className="session-heading"/);
	assert.match(reactShellSource, /className="files-overlay-react"/);
	assert.match(reactShellSource, /function GeneratedArtifactsBlock/);
	assert.match(reactShellSource, /className="generated-artifacts-grid"/);
	assert.match(reactShellSource, /type CenterPane = "chat" \| "files"/);
	assert.match(reactShellSource, /const \[centerPane, setCenterPane\] = useState<CenterPane>\("chat"\)/);
	assert.match(reactShellSource, /className="workspace-tab-strip"/);
	assert.match(reactShellSource, /className="center-files-panel"/);
	assert.match(reactShellSource, /sidePanel === "files" \? \(\s*filesPanelElement/);
	assert.match(reactShellSource, /artifactTileDownloadUrl\(artifact\.path, clientToken\)/);
	assert.match(reactShellSource, /validLinkedArtifact \? "files" : current === "files" \? null : current/);
	assert.match(reactShellSource, /artifactPath \? "files" : current === "files" \? null : current/);
	assert.doesNotMatch(reactShellSource, /nextArtifactPath \? "files"/);
	assert.doesNotMatch(reactShellSource, /Science workbench/);
	assert.match(reactShellStyles, /\.topbar-right\s*\{[\s\S]*?display: none;/);
	assert.match(reactShellStyles, /\.context-strip\s*\{[\s\S]*?display: none;/);
	assert.match(reactShellSource, /aria-label="Files overlay"/);
	assert.match(reactShellSource, /Search files/);
	assert.match(reactShellSource, /function fileHostsForState/);
	assert.match(reactShellSource, /function FileHostStrip/);
	assert.match(reactShellSource, /aria-label="File hosts"/);
	assert.match(reactShellSource, /provider\.family === "ssh" \|\| provider\.family === "byoc"/);
	assert.match(reactShellSource, /cloud:\$\{credential\.id\}:\$\{credential\.defaultBucket\}/);
	assert.match(reactShellSource, /setFileHostId\("local"\)/);
	assert.match(reactShellSource, /Hidden \/ trash/);
	assert.match(reactShellSource, /artifactRecoveryLabel\(item\)/);
	assert.match(reactShellSource, /className="artifact-secondary-actions"/);
	assert.match(reactShellSource, /artifact\.starred \? "Unstar" : "Star"/);
	assert.match(reactShellSource, /renameBusy \? "Renaming" : "Rename"/);
	assert.match(reactShellSource, /<span>Metadata<\/span>/);
	assert.match(reactShellSource, /cloudBusy \? "Exporting" : "Cloud export"/);
	assert.match(reactShellSource, /function CloudStorageModal/);
	assert.match(reactShellSource, /aria-label="Cloud Storage"/);
	assert.match(reactShellSource, /Browse and manage bucket connections used by artifact export/);
	assert.match(reactShellSource, /Go to Credentials/);
	assert.match(reactShellSource, /Test connection/);
	assert.match(reactShellSource, /Delete credential/);
	assert.match(reactShellSource, /Open storage/);
	assert.match(reactShellSource, /function CloudExportModal/);
	assert.match(reactShellSource, /aria-label="Cloud export"/);
	assert.match(reactShellSource, /Destination path/);
	assert.match(reactShellSource, /Configure a target in Customize > Credentials/);
	assert.match(reactShellSource, /<span>Notes<\/span>/);
	assert.match(reactShellSource, /function NotesModal/);
	assert.match(reactShellSource, /aria-label="Artifact notes"/);
	assert.match(reactShellSource, /Write a note linked to this artifact/);
	assert.match(reactShellSource, /Existing notes/);
	assert.match(reactShellSource, /function NotePreviewModal/);
	assert.match(reactShellSource, /aria-label="Note preview"/);
	assert.match(reactShellSource, /aria-label="Note target context"/);
	assert.match(reactShellSource, /Open artifact/);
	assert.match(reactShellSource, /event\.metaKey \|\| event\.ctrlKey/);
	assert.match(reactShellSource, /hideBusy \? "Hiding" : "Hide"/);
	assert.match(reactShellSource, /deleteBusy \? "Deleting" : "Delete"/);
	assert.match(reactShellSource, /className="artifact-editor"/);
	assert.match(reactShellSource, /aria-label="Artifact refinement"/);
	assert.match(reactShellSource, /Loading preview/);
	assert.match(reactShellSource, /Preview truncated/);
	assert.match(reactShellSource, /textSelectionFromSelectedText\(filePreview\.content/);
	assert.match(reactShellSource, /className="artifact-text-preview"/);
	assert.match(reactShellSource, /function HtmlArtifactPreview/);
	assert.match(reactShellSource, /htmlAnnotationBridgeScript/);
	assert.match(reactShellSource, /injectHtmlAnnotationBridge/);
	assert.match(reactShellSource, /htmlSelectionFromFrameMessage/);
	assert.match(reactShellSource, /kind: "html-annot-selected"/);
	assert.match(reactShellSource, /const selectorLine = `selector: \$\{message\.selector\}`/);
	assert.match(reactShellSource, /sandbox="allow-scripts"/);
	assert.match(reactShellSource, /<span>\{annotations\.length\} annotation/);
	assert.match(reactShellSource, /\{annotating \? "Annotating" : "Annotate"\}/);
	assert.match(reactShellSource, /htmlSelectorFromAnnotation/);
	assert.match(reactShellSource, /className="html-artifact-frame"/);
	assert.match(reactShellSource, /Save note/);
	assert.match(reactShellSource, /Draft edit/);
	assert.match(reactShellSource, /Apply edit/);
	assert.match(reactShellSource, /className="media-annotation-toolbar"/);
	assert.match(reactShellSource, /className=\{cx\("media-annotation-overlay"/);
	assert.match(reactShellSource, /<PdfArtifactPreview/);
	assert.doesNotMatch(reactShellSource, /artifact-pdf-preview" title/);
	assert.match(pdfPreviewSource, /getDocument/);
	assert.match(pdfPreviewSource, /TextLayer/);
	assert.match(pdfPreviewSource, /data-pdf-page-number/);
	assert.match(pdfPreviewSource, /rectsFromClientRects/);
	assert.match(pdfPreviewSource, /pdf-page-region-overlay/);
	assert.match(reactShellSource, /<RdkitMoleculePreview/);
	assert.match(reactShellSource, /<ThreeDmolPreview/);
	assert.match(reactShellSource, /<KetcherMoleculeEditor/);
	assert.match(reactShellSource, /function AudioArtifactPreview/);
	assert.match(reactShellSource, /function VideoArtifactPreview/);
	assert.match(reactShellSource, /function SpreadsheetArtifactPreview/);
	assert.match(reactShellSource, /function NotebookArtifactPreview/);
	assert.match(reactShellSource, /function LatexArtifactPreview/);
	assert.match(reactShellSource, /@nightingale-elements\/nightingale-msa/);
	assert.match(reactShellSource, /function MsaSciencePreview/);
	assert.match(reactShellSource, /data-testid="msa-preview"/);
	assert.match(reactShellSource, /MSA alignment preview/);
	assert.match(reactShellSource, /saveMoleculeArtifact/);
	assert.match(reactShellSource, /artifactPath: artifact\.path/);
	assert.match(scienceViewersSource, /@rdkit\/rdkit/);
	assert.match(scienceViewersSource, /3dmol\/build\/3Dmol\.js/);
	assert.match(scienceViewersSource, /ketcher-react/);
	assert.match(scienceViewersSource, /ketcher-standalone/);
	assert.match(scienceViewersSource, /StandaloneStructServiceProvider/);
	assert.match(scienceViewersSource, /setMolecule/);
	assert.match(scienceViewersSource, /getMolfile/);
	assert.match(scienceViewersSource, /getSmiles/);
	assert.match(scienceViewersSource, /RDKit_minimal\.wasm\?url/);
	assert.match(scienceViewersSource, /STRUCTURE_STYLE_OPTIONS/);
	assert.match(scienceViewersSource, /Surface/);
	assert.match(scienceViewersSource, /addSurface/);
	assert.match(scienceViewersSource, /science-viewer-toolbar/);
	assert.match(reactShellSource, /Use in chat/);

	assert.match(reactShellStyles, /\.files-overlay-react/);
	assert.match(reactShellStyles, /\.files-overlay-react-body/);
	assert.match(reactShellStyles, /\.file-host-strip/);
	assert.match(reactShellStyles, /\.file-host-status/);
	assert.match(reactShellStyles, /\.artifact-recovery-list/);
	assert.match(reactShellStyles, /\.artifact-secondary-actions/);
	assert.match(reactShellStyles, /\.cloud-export-modal/);
	assert.match(reactShellStyles, /\.cloud-export-targets/);
	assert.match(reactShellStyles, /\.cloud-storage-modal/);
	assert.match(reactShellStyles, /\.cloud-storage-row/);
	assert.match(reactShellStyles, /\.cloud-storage-status/);
	assert.match(reactShellStyles, /\.notes-modal/);
	assert.match(reactShellStyles, /\.notes-modal-row/);
	assert.match(reactShellStyles, /\.note-preview-modal/);
	assert.match(reactShellStyles, /\.note-preview-context/);
	assert.match(reactShellStyles, /\.artifact-refinement-panel/);
	assert.match(reactShellStyles, /\.artifact-text-preview/);
	assert.match(reactShellStyles, /\.html-artifact-preview/);
	assert.match(reactShellStyles, /\.html-artifact-actions/);
	assert.match(reactShellStyles, /\.html-artifact-frame/);
	assert.match(reactShellStyles, /\.media-annotation-overlay/);
	assert.match(reactShellStyles, /\.pdf-rendered-page/);
	assert.match(reactShellStyles, /\.pdf-text-highlight/);
	assert.match(reactShellStyles, /\.science-viewer-mode/);
	assert.match(reactShellStyles, /\.science-render-stage/);
	assert.match(reactShellStyles, /\.msa-render-stage/);
	assert.match(reactShellStyles, /\.msa-label-gutter/);
	assert.match(reactShellStyles, /\.msa-web-component/);
	assert.match(reactShellStyles, /\.ketcher-editor-stage/);
	assert.match(reactShellStyles, /\.rdkit-svg/);
	assert.match(reactShellStyles, /\.media-file-preview/);
	assert.match(reactShellStyles, /\.spreadsheet-preview/);
	assert.match(reactShellStyles, /\.notebook-artifact-preview/);
	assert.match(reactShellStyles, /\.latex-artifact-preview/);
});

test("React workbench source owns chat activity, notebook, compute, and connector approval surfaces", () => {
	assert.match(reactShellSource, /placeholder="Ask about papers, evidence, code, data, or a reproduction plan"/);
	assert.match(reactShellSource, /aria-label="Open model menu"/);
	assert.match(reactShellSource, /aria-label="Open session options"/);
	assert.match(reactShellSource, /<span>Default<\/span>/);
	assert.match(reactShellSource, /<span>More models<\/span>/);
	assert.match(reactShellSource, /<span>Delegation<\/span>/);
	assert.match(reactShellSource, /<span>Auto-review<\/span>/);
	assert.match(reactShellSource, /<span>Memory<\/span>/);
	assert.match(reactShellSource, /<span>Specialist<\/span>/);
	assert.match(reactShellSource, /<span>Compute<\/span>/);
	assert.match(reactShellSource, /\/api\/chat\/config/);
	assert.match(reactShellSource, /aria-label="Open composer actions"/);
	assert.match(reactShellSource, /<span>Attach files<\/span>/);
	assert.match(reactShellSource, /<span>Your files<\/span>/);
	assert.match(reactShellSource, /<span>View plan<\/span>/);
	assert.match(reactShellSource, /<span>Request review<\/span>/);
	assert.match(reactShellSource, /<span>Save as skill<\/span>/);
	assert.match(reactShellSource, /\/api\/chat\/plan\/generate/);
	assert.match(reactShellSource, /\/api\/chat\/plan\/action/);
	assert.match(reactShellSource, /\/api\/chat\/plan\/step/);
	assert.match(reactShellSource, /function WorkbenchPlanArtifactPreview/);
	assert.match(reactShellSource, /function launcherQueueItems/);
	assert.match(reactShellSource, /function queueActivityItems/);
	assert.match(reactShellSource, /state\.sessionActivity/);
	assert.match(reactShellSource, /function transcriptAnnotationsForMessage/);
	assert.match(reactShellSource, /\/api\/transcript\/annotation/);
	assert.match(reactShellSource, /Bookmark transcript message/);
	assert.match(reactShellSource, /data-testid="transcript-annotations"/);
	assert.match(reactShellSource, /Use this transcript bookmark as context/);
	assert.match(reactShellSource, /<p className="eyebrow">Research queue<\/p>/);
	assert.match(reactShellSource, /badge: "Plan ready"/);
	assert.match(reactShellSource, /All caught up/);
	assert.match(reactShellSource, /No plans, compute jobs, or session messages need attention/);
	assert.match(reactShellSource, /onOpenProject\(item\.project, item\.run, item\.artifactPath\)/);
	assert.match(reactShellSource, /function GlobalCommandPalette/);
	assert.match(reactShellSource, /function commandPaletteGroups/);
	assert.match(reactShellSource, /placeholder="Search projects, artifacts, sessions…"/);
	assert.match(reactShellSource, /aria-label="Search projects, artifacts, and sessions"/);
	assert.match(reactShellSource, /event\.key\.toLowerCase\(\) !== "k"/);
	assert.match(reactShellSource, /commandMatches\(query, \[project\.name, project\.description, project\.id\]\)/);
	assert.match(reactShellSource, /commandMatches\(query, \[run\.title, run\.taskSummary, run\.slug, runStatusLabel\(run\)\]\)/);
	assert.match(reactShellSource, /commandMatches\(query, \[artifact\.title, artifact\.displayName \?\? "", artifact\.name, artifact\.path/);
	assert.match(reactShellSource, /openProjectRun\(item\.project, item\.run, item\.artifact\.path\)/);
	assert.match(reactShellSource, /<span>Approve plan<\/span>/);
	assert.match(reactShellSource, /<span>Reject plan<\/span>/);
	assert.match(reactShellSource, /<span>Reopen plan<\/span>/);
	assert.match(reactShellSource, /aria-label="Plan approval actions"/);
	assert.match(reactShellSource, /workbenchPlanStepOptions/);
	assert.match(reactShellSource, /\/api\/chat\/review\/request/);
	assert.match(reactShellSource, /\/skill:skill-creator/);
	assert.match(reactShellSource, /aria-label="Stop running turn"/);
	assert.match(reactShellSource, /data-testid="tool-activity-list"/);
	assert.match(reactShellSource, /Research activity/);
	assert.match(reactShellSource, /data-testid="chat-connector-approval-card"/);
	assert.match(reactShellSource, /Allow tool/);
	assert.match(reactShellSource, /Allow connector/);
	assert.match(reactShellSource, /Open Permissions/);
	assert.match(reactShellSource, /Retry approved tool/);
	assert.match(reactShellSource, /function NotebookPanel/);
	assert.match(reactShellSource, /aria-label="Notebook language"/);
	assert.match(reactShellSource, /aria-label="Notebook purpose"/);
	assert.match(reactShellSource, /Notebook output appears here after a cell runs/);
	assert.match(reactShellSource, /function ComputePanel/);
	assert.match(reactShellSource, /aria-label="Compute view"/);
	assert.match(reactShellSource, /Open remote/);
	assert.match(reactShellSource, /Run a notebook cell to create a compute job record/);
	assert.match(reactShellSource, /function CustomizePanel/);
	assert.match(reactShellSource, /Feynman Bio Tools/);

	assert.match(reactShellStyles, /\.tool-list/);
	assert.match(reactShellStyles, /\.transcript-annotations/);
	assert.match(reactShellStyles, /\.transcript-annotation-row/);
	assert.match(reactShellStyles, /\.topbar-menu-panel/);
	assert.match(reactShellStyles, /\.topbar-menu-grid/);
	assert.match(reactShellStyles, /\.workspace-tab-strip/);
	assert.match(reactShellStyles, /\.center-files-panel \.files-panel/);
	assert.match(reactShellStyles, /\.composer-menu/);
	assert.match(reactShellStyles, /\.composer\s*\{[\s\S]*?align-self: end;/);
	assert.match(reactShellStyles, /\.composer\s*\{[\s\S]*?background: #181d17;/);
	assert.match(reactShellStyles, /\.composer textarea\s*\{[\s\S]*?background: transparent;/);
	assert.match(reactShellStyles, /\.composer \.composer-tools button\s*\{[\s\S]*?background: #252d23;/);
	assert.match(reactShellStyles, /\.launcher-queue/);
	assert.match(reactShellStyles, /\.launcher-queue-card/);
	assert.match(reactShellStyles, /\.command-palette-backdrop/);
	assert.match(reactShellStyles, /\.command-palette-row/);
	assert.match(reactShellStyles, /\.workbench-plan-preview/);
	assert.match(reactShellStyles, /\.workbench-plan-step-actions/);
	assert.match(reactShellStyles, /\.tool-approval-callout/);
	assert.match(reactShellSource, /className="panel-body science-panel notebook-panel"/);
	assert.match(reactShellStyles, /\.notebook-code/);
	assert.match(reactShellStyles, /\.compute-panel/);
	assert.match(reactShellStyles, /\.customize-panel/);
});
