const PREVIEW_EXTENSIONS = new Set([".bed", ".cdxml", ".cif", ".csv", ".cxsmiles", ".ent", ".faa", ".fa", ".fasta", ".fna", ".gb", ".gbk", ".gff", ".gff3", ".html", ".htm", ".ipynb", ".iqtree", ".json", ".jsonl", ".ket", ".latex", ".md", ".mmcif", ".mol", ".mjs", ".newick", ".nwk", ".out", ".pdb", ".rxn", ".sdf", ".smi", ".smiles", ".tex", ".tree", ".treefile", ".txt", ".tsv", ".vcf"]);

const CONTENT_TYPES_BY_EXTENSION: Record<string, string> = {
	".aac": "audio/aac",
	".aiff": "audio/aiff",
	".bed": "text/x-bed; charset=utf-8",
	".cdxml": "chemical/x-cdxml; charset=utf-8",
	".cif": "chemical/x-mmcif; charset=utf-8",
	".csv": "text/csv; charset=utf-8",
	".cxsmiles": "chemical/x-daylight-smiles; charset=utf-8",
	".ent": "chemical/x-pdb; charset=utf-8",
	".fa": "text/x-fasta; charset=utf-8",
	".faa": "text/x-fasta; charset=utf-8",
	".fasta": "text/x-fasta; charset=utf-8",
	".fna": "text/x-fasta; charset=utf-8",
	".gb": "chemical/seq-na-genbank; charset=utf-8",
	".gbk": "chemical/seq-na-genbank; charset=utf-8",
	".gff": "text/x-gff; charset=utf-8",
	".gff3": "text/x-gff; charset=utf-8",
	".flac": "audio/flac",
	".gif": "image/gif",
	".html": "text/html; charset=utf-8",
	".htm": "text/html; charset=utf-8",
	".ipynb": "application/x-ipynb+json; charset=utf-8",
	".iqtree": "text/plain; charset=utf-8",
	".jpeg": "image/jpeg",
	".jpg": "image/jpeg",
	".json": "application/json; charset=utf-8",
	".jsonl": "application/json; charset=utf-8",
	".ket": "application/json; charset=utf-8",
	".latex": "text/x-tex; charset=utf-8",
	".m4a": "audio/mp4",
	".m4v": "video/mp4",
	".md": "text/plain; charset=utf-8",
	".mmcif": "chemical/x-mmcif; charset=utf-8",
	".mol": "chemical/x-mdl-molfile; charset=utf-8",
	".mov": "video/quicktime",
	".mp3": "audio/mpeg",
	".mp4": "video/mp4",
	".mpeg": "video/mpeg",
	".mpg": "video/mpeg",
	".newick": "text/x-newick; charset=utf-8",
	".nwk": "text/x-newick; charset=utf-8",
	".npy": "application/x-npy",
	".npz": "application/x-npz",
	".oga": "audio/ogg",
	".ogg": "audio/ogg",
	".ogv": "video/ogg",
	".opus": "audio/ogg",
	".pdf": "application/pdf",
	".pdb": "chemical/x-pdb; charset=utf-8",
	".png": "image/png",
	".rxn": "chemical/x-mdl-rxnfile; charset=utf-8",
	".sdf": "chemical/x-mdl-sdfile; charset=utf-8",
	".smi": "chemical/x-daylight-smiles; charset=utf-8",
	".smiles": "chemical/x-daylight-smiles; charset=utf-8",
	".svg": "image/svg+xml; charset=utf-8",
	".tex": "text/plain; charset=utf-8",
	".tree": "text/x-newick; charset=utf-8",
	".treefile": "text/x-newick; charset=utf-8",
	".tsv": "text/tab-separated-values; charset=utf-8",
	".txt": "text/plain; charset=utf-8",
	".vcf": "text/x-vcf; charset=utf-8",
	".wav": "audio/wav",
	".webm": "video/webm",
	".webp": "image/webp",
	".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
};

const LANGUAGE_BY_EXTENSION: Record<string, string> = {
	".bed": "bed",
	".cdxml": "cdxml",
	".cif": "mmcif",
	".csv": "csv",
	".cxsmiles": "smiles",
	".ent": "pdb",
	".fa": "fasta",
	".faa": "fasta",
	".fasta": "fasta",
	".fna": "fasta",
	".gb": "genbank",
	".gbk": "genbank",
	".gff": "gff",
	".gff3": "gff",
	".html": "html",
	".htm": "html",
	".ipynb": "jupyter-notebook",
	".iqtree": "iqtree",
	".json": "json",
	".jsonl": "json",
	".ket": "ket",
	".latex": "latex",
	".md": "markdown",
	".mmcif": "mmcif",
	".mjs": "javascript",
	".mol": "mol",
	".newick": "newick",
	".nwk": "newick",
	".npy": "numpy",
	".npz": "numpy-archive",
	".pdb": "pdb",
	".pdf": "pdf",
	".rxn": "rxn",
	".sdf": "sdf",
	".smi": "smiles",
	".smiles": "smiles",
	".tex": "latex",
	".tree": "newick",
	".treefile": "newick",
	".tsv": "tsv",
	".vcf": "vcf",
	".xlsx": "spreadsheet",
};

export function isWorkbenchPreviewExtension(extension: string): boolean {
	return PREVIEW_EXTENSIONS.has(extension);
}

export function contentTypeForExtension(extension: string): string {
	return CONTENT_TYPES_BY_EXTENSION[extension] ?? "application/octet-stream";
}

export function languageForExtension(extension: string): string {
	return LANGUAGE_BY_EXTENSION[extension] ?? (extension.replace(/^\./, "") || "text");
}
